In [7]:
import torch

# Data
x = torch.tensor([1., 2., 3.])
y_true = torch.tensor([2., 4., 6.])

# Parameters
w = torch.tensor(0.5, requires_grad=True)
b = torch.tensor(0.1, requires_grad=True)

# Learning rate
lr = 0.01

# Training loop
for epoch in range(100):
    # 1️⃣ Forward pass: compute prediction
    y_pred = w * x + b
    
    # 2️⃣ Compute loss (Mean Squared Error)
    loss = torch.mean((y_pred - y_true) ** 2)
    
    # 3️⃣ Backward pass: compute gradients
    loss.backward()
    
    # 4️⃣ Update weights manually
    with torch.no_grad():  # disable gradient tracking during update
        w -= lr * w.grad
        b -= lr * b.grad
        
    
    # 5️⃣ Zero gradients for next iteration
    w.grad.zero_()
    b.grad.zero_()
    
    # Print loss every 20 epochs
    if (epoch+1) % 20 == 0:
        print(f'Epoch {epoch+1}, Loss: {loss.item()}')

print("Trained weight:", w.item())
print("Trained bias:", b.item())


Epoch 20, Loss: 0.16606862843036652
Epoch 40, Loss: 0.04921847954392433
Epoch 60, Loss: 0.04377974569797516
Epoch 80, Loss: 0.03975312411785126
Epoch 100, Loss: 0.03610431030392647
Trained weight: 1.7798343896865845
Trained bias: 0.500461995601654


In [8]:
import torch

scaler=torch.tensor(0.1, dtype=torch.int64)
print(scaler)

# scaler  which have single value
#vector which have multiple value
# list which have multiple value and different data type
# tensor which have multiple value and same data type and more efficient than list

vector=torch.tensor([2,4])

scaler.ndim
vector.ndim # ndim tell the dimesional of given tensor


scaler.item() # item() only work for single value tensor

# some basic concept :
print("data type of scaler :",scaler.dtype)
print("data type of vector :",vector.dtype)







tensor(0)
data type of scaler : torch.int64
data type of vector : torch.int64


In [9]:
import torch

x=torch.tensor([1, 2, 3, 4, 5])
y_true=torch.tensor([3, 6, 9, 12, 15])

w=torch.tensor(0.5, requires_grad=True)
b=torch.tensor(0.1, requires_grad=True)

#forwad pass
y_perdict=w*x + b

# loss calculate 
loss=torch.mean((y_perdict - y_true)**2)

learning_rate=0.01
epochs=100

for epoch in range(epochs):
    # forward pass
    y_perdict=w*x + b

    # loss calculate 
    loss=torch.mean((y_perdict - y_true)**2)

    # backward pass:
    loss.backward()

    #adjust weight and bias
    with torch.no_grad():
        w-=learning_rate * w.grad
        b-=learning_rate * b.grad

    # zero gradients
    w.grad.zero_()
    b.grad.zero_()

    if (epoch+1) % 20 ==0:
        print(f'Epoch {epoch+1}, Loss: {loss.item()}')
print("Trained weight:", w.item())
print("Trained bias:", b.item())


Epoch 20, Loss: 0.08904146403074265
Epoch 40, Loss: 0.07570742070674896
Epoch 60, Loss: 0.06611595302820206
Epoch 80, Loss: 0.0577394962310791
Epoch 100, Loss: 0.05042418837547302
Trained weight: 2.854706048965454
Trained bias: 0.5245567560195923


In [10]:
value_1=torch.tensor([[1,2],
                      [2,3],
                      [3,4],
                      [4,5]])
value_t=value_1.T
print(value_t)
multiplication=torch.matmul(value_1, value_1.T)
print(multiplication)

test=torch.tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])

multi=torch.multiply(test, test)
print(multi)

matrix_multi=torch.matmul(test, test.reshape(4,2))
print(matrix_multi)

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[ 5,  8, 11, 14],
        [ 8, 13, 18, 23],
        [11, 18, 25, 32],
        [14, 23, 32, 41]])
tensor([[ 1,  4,  9, 16],
        [ 4,  9, 16, 25]])
tensor([[29, 39],
        [39, 53]])


In [11]:
x=torch.tensor( [[[[1, 2],
     [2, 3],
     [3, 4],
     [4, 5]]]])
#its dimesinal[batch, channels, height, width] = [1, 1, 4, 2]

y=torch.tensor( [8, 13, 18, 23])

w=torch.tensor( [1.0, 2.0], requires_grad=True)
b=torch.tensor(0.5, requires_grad=True)
y_perdict=x*w +b
print(y_perdict)

print(x.size())

#print(x[1]).. when we want to access specific element

tensor([[[[ 1.5000,  4.5000],
          [ 2.5000,  6.5000],
          [ 3.5000,  8.5000],
          [ 4.5000, 10.5000]]]], grad_fn=<AddBackward0>)
torch.Size([1, 1, 4, 2])


tensor rendom is used in nural netwrok to impelemnt in random values and used in nural network it important topics:

In [12]:
random_tensor=torch.rand(8,9)
random_tensor
random_tensor.shape
random_tensor.dtype
random_tensor.ndim
random_tensor @ random_tensor.T

tensor([[2.8236, 2.7149, 3.7474, 1.7408, 2.4027, 1.8963, 1.8735, 1.6603],
        [2.7149, 3.2659, 3.6997, 1.9448, 2.7467, 1.5096, 2.1131, 1.5159],
        [3.7474, 3.6997, 5.5126, 2.2819, 3.6274, 2.7303, 2.8956, 2.5139],
        [1.7408, 1.9448, 2.2819, 2.4740, 1.8494, 1.6476, 1.4681, 1.2352],
        [2.4027, 2.7467, 3.6274, 1.8494, 2.9184, 1.8221, 1.9948, 1.4948],
        [1.8963, 1.5096, 2.7303, 1.6476, 1.8221, 2.1094, 1.3043, 1.4840],
        [1.8735, 2.1131, 2.8956, 1.4681, 1.9948, 1.3043, 1.8717, 1.4679],
        [1.6603, 1.5159, 2.5139, 1.2352, 1.4948, 1.4840, 1.4679, 1.4445]])

In [13]:
from sklearn.cluster import KMeans
import numpy as np

X = np.array([[40],[42],[45],[85],[88],[90]])

kmeans = KMeans(n_clusters=2)
kmeans.fit(X)

print(kmeans.labels_)      # cluster assignment
print(kmeans.cluster_centers_)  # centroids


[0 0 0 1 1 1]
[[42.33333333]
 [87.66666667]]


In [1]:
import torch

# Input features (X)
house_size = torch.tensor([33.,44.,55.,66.,77.,88.,99.,110.])
number_rooms = torch.tensor([2.,3.,4.,5.,6.,7.,7.,16.])

# Stack features -> shape (8, 2)
X = torch.stack((house_size, number_rooms), dim=1)

# Target (y)
y_true = torch.tensor([150000.,190000.,100000.,122000.,10100.,10000.,210000.,220000.])

# Initialize weights (2 inputs → 2 weights)
W = torch.randn(2, requires_grad=True)
b = torch.randn(1, requires_grad=True)

learning_rate = 0.00001
epochs = 100

for epoch in range(epochs):

    # Forward pass
    y_pred = X @ W + b      # (8,2) @ (2,) + b → (8,)

    # Mean Squared Error Loss
    loss = torch.mean((y_pred - y_true) ** 2)

    # Backward pass
    loss.backward()

    # Update parameters
    with torch.no_grad():
        W -= learning_rate * W.grad
        b -= learning_rate * b.grad

    # Zero gradients
    W.grad.zero_()
    b.grad.zero_()

    if (epoch + 1)%20  == 0:
        print(f"Epoch {epoch+1}, Loss: {loss.item()}")


Epoch 20, Loss: 7462383616.0
Epoch 40, Loss: 7326896128.0
Epoch 60, Loss: 7325513728.0
Epoch 80, Loss: 7325100544.0
Epoch 100, Loss: 7324696576.0


In [15]:
y=np.array([2,3,4])
z=np.array([1,2,5])
# main difference between vector and scaler multiplication
# vector(y*z) give output multiplication
#scaler give real life output(Y@z)
print("output using vector =",y*z)
print("output using scaler =",y@z)

Engine_Size=torch.tensor([1000, 1500, 1800, 2000, 2500, 3000, 3500, 4000])
Horsepower=torch.tensor([70,   90,   110,  130,  160,  200,  250,  300])
Car_Age=torch.tensor([10,   8,    6,    5,    4,    3,    2,    1])
w=torch.tensor([0.5], requires_grad=True)
b=torch.tensor(0.5, requires_grad=True)
output=w*Engine_Size + w*Horsepower + w*Car_Age + b

x=torch.stack((Engine_Size, Horsepower, Car_Age), dim=1)
outputs=x @ w+ b
print(outputs)
print(output)

output using vector = [ 2  6 20]
output using scaler = 28


RuntimeError: size mismatch, got input (8), mat (8x3), vec (1)

In [ ]:
# input features
Engine_Size=torch.tensor([1000, 1500, 1800, 2000, 2500, 3000, 3500, 4000])
Horsepower=torch.tensor([70,   90,   110,  130,  160,  200,  250,  300])
Car_Age=torch.tensor([10,   8,    6,    5,    4,    3,    2,    1])

#perdicted:
Price=torch.tensor([5000, 7000, 9000, 11000, 15000, 20000, 28000, 35000])

# first we intailize weight and bias
w=torch.tensor(0.01, requires_grad=True)
b=torch.tensor(0.1, requires_grad=True)

# learning rate
lr=0.0001
epochs=100

for epoch in range(epochs):
    #forword pass
    x=torch.stack((Engine_Size, Horsepower, Car_Age), dim=1)
    y_perdict=w @ x + b

    # find loss
    loss=torch.mean((y_perdict - Price)**2)

    #bacword pass:
    loss.backward()

    #adjust weight:
    with torch.no_grad():
        w-=lr * w.grad
        b-=lr * b.grad

    #gradient intialize zero:
    w.grad.zero_()
    b.grad.zero_()

    if (epoch + 1) % 20 == 0:
        print(f"Epochs ={epoch +1} , loss {loss}  ")

    
print("weight : ",w )
print("Bias : ",b)






RuntimeError: both arguments to matmul need to be at least 1D, but they are 0D and 2D

In [ ]:
import torch

# -------------------------------
# Input features
# -------------------------------
Engine_Size = torch.tensor([1000., 1500., 1800., 2000., 2500., 3000., 3500., 4000.])
Horsepower  = torch.tensor([70.,   90.,   110.,  130.,  160.,  200.,  250.,  300.])
Car_Age     = torch.tensor([10.,    8.,    6.,    5.,    4.,    3.,    2.,    1.])

# Target
Price = torch.tensor([5000., 7000., 9000., 11000., 15000., 20000., 28000., 35000.])

# -------------------------------
# Feature Scaling (Mean Normalization)
# -------------------------------
Engine_Size = (Engine_Size - Engine_Size.mean()) / Engine_Size.std()
Horsepower  = (Horsepower  - Horsepower.mean())  / Horsepower.std()
Car_Age     = (Car_Age     - Car_Age.mean())     / Car_Age.std()

# -------------------------------
# Stack features -> X matrix (8 x 3)
# -------------------------------
X = torch.stack((Engine_Size, Horsepower, Car_Age), dim=1)

# -------------------------------
# Initialize weights and bias
# -------------------------------
W = torch.randn(3, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# -------------------------------
# Training parameters
# -------------------------------
lr = 0.01
epochs = 1000

# -------------------------------
# Training loop
# -------------------------------
for epoch in range(epochs):

    # Forward pass
    y_pred = X @ W + b

    # Mean Squared Error loss
    loss = torch.mean((y_pred - Price) ** 2)

    # Backward pass
    loss.backward()

    # Gradient descent update
    with torch.no_grad():
        W -= lr * W.grad
        b -= lr * b.grad

    # Zero gradients
    W.grad.zero_()
    b.grad.zero_()

    if (epoch + 1) % 200 == 0:
        print(f"Epoch {epoch+1}, Loss: {loss.item()}")

# -------------------------------
# Final parameters
# -------------------------------

print("\nFinal Weights:", W)
print("Final Bias:", b)


Epoch 200, Loss: 3330102.0
Epoch 400, Loss: 2151992.5
Epoch 600, Loss: 1448904.75
Epoch 800, Loss: 996520.6875
Epoch 1000, Loss: 705249.875

Final Weights: tensor([4418.8936, 7359.3374, 1304.8568], requires_grad=True)
Final Bias: tensor([16249.9766], requires_grad=True)


In [ ]:
import torch
#input Features
year_experience = torch.tensor([1,2,3,5,7,10,12,15], dtype=torch.float32).unsqueeze(1)  # (8,1)
Education_level = torch.tensor([1,1,2,2,2,3,3,3], dtype=torch.float32).unsqueeze(1)
Age             = torch.tensor([22,24,26,30,34,40,45,50], dtype=torch.float32).unsqueeze(1)
skill_score     = torch.tensor([5,6,6,7,8,8,9,9], dtype=torch.float32).unsqueeze(1)


#perdicted:
Target=torch.tensor([25000, 30000, 38000, 50000, 65000, 90000, 110000, 130000])

#feature scalling:
year_experience = (year_experience - year_experience.mean()) / year_experience.std()
Education_level = (Education_level - Education_level.mean()) / Education_level.std()
Age = (Age - Age.mean()) / Age.std()
skill_score = (skill_score - skill_score.mean()) / skill_score.std()


#stacking:
X = torch.cat((year_experience, Education_level, Age, skill_score), dim=1)

#intalize weight:
W=torch.rand(4 , requires_grad=True)
b=torch.rand(1, requires_grad=True)

#intialize :
lr=0.001
epochs=1000

for epoch in range(epochs):
    #forward pass:
    Perdict = X @ W + b  

    # loss perduction:
    loss=torch.mean(Perdict - Target)**2

    #backward pass:
    loss.backward()

    # weight Adjust:
    with torch.no_grad():
        W-=lr * W.grad
        b-=lr * b.grad

    # zero gradient:
    W.grad.zero_()
    b.grad.zero_()

    if(epoch+1)%200==0:
        print(f"Epochs {epoch+1} , lost : {loss}")



print("final weight ",W)
print("Final bias ",b)

    

Epochs 200 , lost : 24895644.0
Epochs 400 , lost : 15510846.0
Epochs 600 , lost : 10632452.0
Epochs 800 , lost : 7551273.5
Epochs 1000 , lost : 5567382.5
final weight  tensor([18036.2500,  1281.9674, 18221.6797,  1262.9478], requires_grad=True)
Final bias  tensor([67249.8125], requires_grad=True)


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# Data
X = torch.tensor(
[
 [1,  1, 22, 5],
 [2,  1, 24, 6],
 [3,  2, 26, 6],
 [5,  2, 30, 7],
 [7,  2, 34, 8],
 [10, 3, 40, 8],
 [12, 3, 45, 9],
 [15, 3, 50, 9]
], dtype=torch.float32)

y = torch.tensor(
[2500, 3000, 3800, 5000, 6500, 9000, 11000, 13000],
dtype=torch.float32
)

# Simple Linear Layer (no class)
model = nn.Linear(4, 1)

# Loss & Optimizer
loss_fn = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

# Training
epochs = 1000
for epoch in range(epochs):

    y_pred = model(X).squeeze()

    loss = loss_fn(y_pred, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 200 == 0:
        print(f"Epoch {epoch+1}, Loss: {loss.item():.2f}")

# Final Weights & Bias
print("Weights:", model.weight.data)
print("Bias:", model.bias.data)


Epoch 200, Loss: nan
Epoch 400, Loss: nan
Epoch 600, Loss: nan
Epoch 800, Loss: nan
Epoch 1000, Loss: nan
Weights: tensor([[nan, nan, nan, nan]])
Bias: tensor([nan])


In [35]:
import torch

# input features
Year_of_experiment=torch.tensor([21,34,12,20,13,15],dtype=torch.float32)
Age=torch.tensor([23,43,22,11,23,41],dtype=torch.float32)
Education_level=torch.tensor([1,1,2,2,2,3],dtype=torch.float32)

# stacking of inputs
X=torch.stack([Year_of_experiment,Age,Education_level],dim=1)

#SCALLING:
X=(X-X.mean(dim=0))/ X.std(dim=0)

#perdict value
y_target=torch.tensor([2000,12000,10030, 10070,10600,12000],dtype=torch.float32)

#intialize weight
w=torch.rand(3, requires_grad=True)
b=torch.rand(1,requires_grad=True)

lr=0.001
epochs=1000
lembda=0.5
for epoch in range(epochs):
    
    #farward pass data
    y_perdict=X @ w +b

    #loss calculate:
    loss=torch.mean((y_perdict - y_target)**2)


    loss_regulization=loss + lembda * torch.sum(w**2)


    #take data backward:
    loss_regulization.backward()

    #update learning rate:
    with torch.no_grad():
        w-=lr *w.grad
        b-=lr *b.grad

    
    #take gradient zero:
    w.grad.zero_()
    b.grad.zero_()
    
    if (epoch+1)%100==0:
        print(f"epoch , {epoch+1}  , loss  : {loss_regulization.item():.3f}")

print("Weight : ",w)
print("Bias  : ",b)




epoch , 100  , loss  : 70551968.000
epoch , 200  , loss  : 49972820.000
epoch , 300  , loss  : 36241996.000
epoch , 400  , loss  : 27072792.000
epoch , 500  , loss  : 20945264.000
epoch , 600  , loss  : 16847780.000
epoch , 700  , loss  : 14106187.000
epoch , 800  , loss  : 12270849.000
epoch , 900  , loss  : 11041559.000
epoch , 1000  , loss  : 10217816.000
Weight :  tensor([ 277.1129,  757.8405, 1212.3589], requires_grad=True)
Bias  :  tensor([8173.6885], requires_grad=True)


In [ ]:
import torch

# Features (5 samples, 2 features)
X = torch.tensor([
    [2.0, 1.0],
    [3.0, 2.0],
    [4.0, 3.0],
    [5.0, 3.0],
    [6.0, 4.0]
], dtype=torch.float32)

# Labels (0 = Fail, 1 = Pass)
y_true = torch.tensor([0, 0, 0, 1, 1], dtype=torch.float32)

#intialize weight :
w=torch.rand(2,1, requires_grad=True)
b=torch.rand(1,requires_grad=True)
lr=0.1
epochs=100

for epoch in range(epochs):
    #farward pass 
    y_pred=torch.sigmoid(X @ w + b)

    #binary loss
    binary_loss = -torch.mean(-y_true* torch.log(y_pred) + (1 - y_true) * torch.log(1 - y_pred) )
    print(binary_loss)

    #backward pass:
    binary_loss.backward()

    with torch.no_grad():
        w -=w - lr * w.grad
        b -=b - lr * b.grad

    # make gradient zero:
    w.grad.zero_()
    b.grad.zero_()

    if (epoch+ 1)==0:
        print(f" Epoch {epoch +1} , loss {loss}")

print("WEight ",w)
print('bias',b)   





In [ ]:
import torch

# Features (5 samples, 2 features)
X = torch.tensor([
    [2.0, 1.0],
    [3.0, 2.0],
    [4.0, 3.0],
    [5.0, 3.0],
    [6.0, 4.0]
], dtype=torch.float32)

# Labels (0 = Fail, 1 = Pass)
y_true = torch.tensor([0, 0, 0, 1, 1], dtype=torch.float32)

#intialize weight :
w=torch.rand(2,1, requires_grad=True)
b=torch.rand(1,requires_grad=True)
lr=0.1
epochs=1000

for epoch in range(epochs):
    #farward pass 
    y_pred=torch.sigmoid(X @ w + b)

    #binary loss
    binary_loss = -torch.mean(-y_true* torch.log(y_pred) + (1 - y_true) * torch.log(1 - y_pred) )
    print(binary_loss)

    #backward pass:
    binary_loss.backward()

    with torch.no_grad():
        w -=w - lr * w.grad
        b -=b - lr * b.grad

    # make gradient zero:
    w.grad.zero_()
    b.grad.zero_()

    if (epoch+ 1)%100==0:
        print(f" Epoch {epoch +1} , loss {loss}")

print("WEight ",w)
print('bias',b)   





In [ ]:
import torch

# Data
study_hours = torch.tensor([2, 4, 5, 6, 7], dtype=torch.float32)
sleep_hours = torch.tensor([7, 6, 6, 5, 4], dtype=torch.float32)
X = torch.stack((study_hours, sleep_hours), dim=1)
y_true = torch.tensor([0, 0, 1, 1, 1], dtype=torch.float32).view(-1, 1)

# Trained weights and bias
W = torch.tensor([[0.0001 , 0.000009]], dtype=torch.float32)  # fill your W
b = torch.tensor([0], dtype=torch.float32)         # fill your b

# Forward pass
y_pred = torch.sigmoid(X @ W.T + b)

# Convert to class
y_class = (y_pred >= 0.5).float()

# Accuracy
accuracy = (y_class == y_true).sum() / y_true.shape[0] * 100

# Print
print("Predicted Probabilities:\n", y_pred)
print("Predicted Class:\n", y_class)
print(f"Accuracy: {accuracy.item():.2f}%")


Predicted Probabilities:
 tensor([[0.5001],
        [0.5001],
        [0.5001],
        [0.5002],
        [0.5002]])
Predicted Class:
 tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])
Accuracy: 300.00%


In [27]:
a=torch.tensor([1,2,3,4,5,6,7,8])
print(a.shape)

b=a.view(1,-1)
print(b)

c=a.view(4,2)
print(c)


d=a.view(2,4)
print(d)

y_true = torch.tensor([0,0,1,1,1], dtype=torch.float32).view(-1,1)
print(y_true)



torch.Size([8])
tensor([[1, 2, 3, 4, 5, 6, 7, 8]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [1]:
import dlib
print(dlib.__version__)


19.22.99
